#
# SPDX-License-Identifier: GPL-3.0-or-later

title   Install SkorionOS
linux   /%INSTALL_DIR%/boot/x86_64/vmlinuz-linux-skchos
initrd  /%INSTALL_DIR%/boot/x86_64/initramfs-linux-skchos.img
options archisobasedir=%INSTALL_DIR% archisolabel=%ARCHISO_LABEL% cow_spacesize=4G
